development:
  adapter: postgresql
  encoding: unicode
  database: kidsclub_development
  host: localhost
  port: 5432
test:
  adapter: postgresql
  encoding: unicode
  database: kidsclub_test
  host: localhost
  port: 5432